import React from "react";
import Head from "next/head";
import Cards from "../components/cards";
import { Container, Main, Title } from "../components/sharedstyles";

const Home: React.FC = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Cards />
      </Main>
    </Container>
  );
};

export default Home;
