import React from "react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import styled from "styled-components";
import Cards from "../components/cards";
import { Title } from "../components/sharedstyles";

const Root = styled.div`
  display: flex;
  background-image: url("/app-background.webp");
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  height: 100vh;
  width: 100vw;
`;

const ContentWrapper = styled.div`
  margin: auto;
`;

const Home = () => {
  const { data: session } = useSession();
  if (session) {
    return (
      <Root>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ContentWrapper>
          <Title>Trailblazer</Title>
          Signed in as {session.user.name} <br />
          <button onClick={() => signOut()}>Sign out</button>
          <Cards />
        </ContentWrapper>
      </Root>
    );
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  );
};

export default Home;
